@startuml
    class MexmTask{
        -- methods --
        requires
    }
    
    class MexmForkTask
    MexmForkTask --> MexmTask
    
    class SimulationTask
    SimulationTask --> MexmTask

    class VaspSimulationTask
    VaspSimulationTask --> MexmTask
    VaspSimulation *--> VaspSimulationTask

    class LammpsSimulationTask 
    LammpsSimulationTask --> MexmTask
    LammpsSimulation *--> MexmTask

    class MexmWorkflow
    MexmWorkflow --> MexmTask

    class AbstractFactory

    
    class MexmFactory
    
    class MexmOverlord

    class MexmTenant

@enduml