language: python
python:
  - 3.5
  - 3.6
# before install
install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip setup.py install
# command to add dependencies
install:
  - pip install -r requirements.txt
  - pip install ".[test]" .
# command to run tests
script:
  - python -m pytest
after_success:
  - codecov # submit coverage